api/urls.py
from django.urls import path
from .views import mark_safe_location, get_all_safe_locations, get_nearest_safe_location, get_stats, mark_unsafe_location, sos_distress

urlpatterns = [
    path('mark_safe_location', mark_safe_location),
    path('get_nearest_safe_location', get_nearest_safe_location),
    path('mark_unsafe_location', mark_unsafe_location),
    path('get_all_safe_locations', get_all_safe_locations),
    path('get_stats', get_stats),
    path('sos_distress', sos_distress)
]

hackverse/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('api.urls')),
    path('webapp/', include('webapp.urls'))
]

webapp/urls.py
from django.urls import path
from .views import home, get_locations, get_stats

app_name = 'webapp'

urlpatterns = [
    path('',home),
    path('get_locations', get_locations, name="get_locations"),
    path('get_stats', get_stats, name='webapp'),
]

api/models.py
from django.db import models

class Location(models.Model):
    latitude = models.FloatField(null=False)
    longitude = models.FloatField(null=False)
    safe_count = models.IntegerField(default=1)

    def __str__(self):
        return f'Latitude: {self.latitude}, Longitude: {self.longitude}'

class DistressLocation(models.Model):
    latitude = models.FloatField(null=False)
    longitude = models.FloatField(null=False)

    def __str__(self):
        return f'Latitude: {self.latitude}, Longitude: {self.longitude}'

webapp/models.py
from django.db import models

# Create your models here.

api/views.py
from django.shortcuts import render
from django.http import JsonResponse, HttpResponse
from django.db.models import F
import math
from .models import Location, DistressLocation

def haversine(lat1, lon1, lat2, lon2): 
    dLat = (lat2 - lat1) * math.pi / 180.0
    dLon = (lon2 - lon1) * math.pi / 180.0
  
    # convert to radians 
    lat1 = (lat1) * math.pi / 180.0
    lat2 = (lat2) * math.pi / 180.0
  
    # apply formulae 
    a = (pow(math.sin(dLat / 2), 2) + pow(math.sin(dLon / 2), 2) * math.cos(lat1) * math.cos(lat2))
    rad = 6371000
    c = 2 * math.asin(math.sqrt(a)) 
    return rad * c 

def mark_safe_location(request):
    latitude = float(request.GET.get('latitude'))
    longitude = float(request.GET.get('longitude'))

    objects = Location.objects.all()

    flag = False

    for obj in objects:
        print(haversine(obj.latitude, obj.longitude, latitude, longitude))
        if haversine(obj.latitude, obj.longitude, latitude, longitude) < 50:
            obj.safe_count = F('safe_count') + 1
            obj.save()
            flag = True
    
    if not flag:
        Location(latitude = latitude, longitude = longitude).save()
    return HttpResponse()

def get_nearest_safe_location(request):
    objects = Location.objects.all()
    min_dist = 999999999
    loc = None

    latitude = float(request.GET.get('latitude'))
    longitude = float(request.GET.get('longitude'))
    
    for obj in objects:
        h = haversine(latitude, longitude, obj.latitude, obj.longitude)
        if h < min_dist:
            min_dist = h
            loc = obj
    if loc is None:
        return JsonResponse({})
    return JsonResponse({
        'latitude'  : loc.latitude,
        'longitude' : loc.longitude
    })

def mark_unsafe_location(request):
    latitude = float(request.GET.get('latitude'))
    longitude = float(request.GET.get('longitude'))

    objects = Location.objects.all()

    flag = False
    for obj in objects:
        if haversine(obj.latitude, obj.longitude, latitude, longitude) < 50:
            if obj.safe_count == 1:
                obj.delete()
            else:
                obj.safe_count = F('safe_count') - 1
                obj.save()

    return HttpResponse()

def get_all_safe_locations(request):
    res = []

    for obj in Location.objects.all():
        res.append({
            'latitude'  : obj.latitude,
            'longitude' : obj.longitude 
        })
    return JsonResponse(res, safe=False)

def get_stats(request):
    return JsonResponse({
        'number_of_people_in_distress'  : len(DistressLocation.objects.all()),
    })

def sos_distress(request):
    latitude = float(request.GET.get('latitude'))
    longitude = float(request.GET.get('longitude'))

    DistressLocation(latitude=latitude, longitude=longitude).save()
    return HttpResponse()

def get_all_distress_locations(request):
    res = []
    for obj in DistressLocation.objects.all():
        res.append({
            'latitude'  : obj.latitude,
            'longitude' : obj.longitude
        })
    return JsonResponse(res, safe=False)

webapp/views.py
from django.shortcuts import render, HttpResponse
import json
import requests

def home(request):
    return render(request, 'webapp/home.html')

def get_locations(request):
    # res = requests.get('http://'+HOSTED_AT+'get_all_safe_locations')
    # safe_locations = json.dumps(res)
    # return resJson
    # print(safe_locations)
    return render(request, 'webapp/locations.html')

def get_stats(request):
    return JsonResponse({
        'number_of_people_in_distress'  : len(DistressLocation.objects.all()),
    })

webapp/templates/webapp/base.html
<!DOCTYPE html>
<html>
<title>Rescue Portal</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inconsolata">
<style>
body, html {
  height: 100%;
  font-family: "Inconsolata", sans-serif;
}

.bgimg {
  background-position: center;
  background-size: cover;
  background-image: url("/w3images/coffeehouse.jpg");
  min-height: 75%;
}

.menu {
  display: none;
}
</style>
<body>
<!-- Links (sit on top) -->     
<div class="w3-top">
    <div class="w3-row w3-padding w3-black">
      <div class="w3-col s3">
        <a href="/webapp#map" class="w3-button w3-block w3-black">HOME</a>
      </div>
      <div class="w3-col s3">
        <a href="#map" class="w3-button w3-block w3-black">NEARBY LOCATIONS INFO</a>
      </div>
      <div class="w3-col s3">
        <a href="#rescue" class="w3-button w3-block w3-black">HELP IN RESCUE</a>
      </div>
      <div class="w3-col s3">
        <a href="#where" class="w3-button w3-block w3-black">CONTACT US</a>
      </div>
    </div>
</div>


<header class="bgimg w3-display-container" id="map">
</header>

<!-- Add a background color and large text to the whole page -->
<!-- <div class="w3-sand w3-grayscale w3-large"> -->
{% block one %}
{% endblock %}

<div class="w3-container" id="rescue">
    <div class="w3-content" style="max-width:700px">
        <h5 class="w3-center w3-padding-48"><span class="w3-tag w3-wide">HELP IN RESUCE OPS</span></h5>
        <p><strong>Interested in helping in the rescue operations, then click the below button to help the needy along with the Zulip bot</strong>:</p>
        <a href="https://hackverse-gods.zulipchat.com"><h5 class="w3-center w3-padding-64" id="help_rescue"><span class="w3-tag w3-wide"><img style="width: 100px; height: 100px;" src="https://raw.githubusercontent.com/skunkmb/swift-zulip-api/master/assets/zulip-logo.png"></span></h5></a>
        <ol>
            <p>Steps to follow:</p>
            <li>Signup or login with an OAuth</li>
            <li>Click on a message to start chatting with the DistressSOS bot</li>
            <li>Enter '@DistressSOS report', to find locations requesting help</li>
            <li>Enter '@DistressSOS rescue &lt;serial_number&gt;', to remove the location corresponding to that serial number from the distress list</li>
        </ol>
    </div>
</div>
  


<div class="w3-container" id="where" style="padding-bottom:32px;">
    <div class="w3-content" style="max-width:700px">
      <h5 class="w3-center w3-padding-48"><span class="w3-tag w3-wide">WHERE TO CONTACT US</span></h5>
      <p>Toll Free Helpline Number: +91 98765 43210 (24 lines)</p>
      <p>Email ID: help@rescueportal.com</p>
      <p><strong>Provide more information of the emergency:</strong>:</p>
      <form>
        <p><input class="w3-input w3-padding-16 w3-border" type="text" placeholder="Name" required name="Name"></p>
        <p><input class="w3-input w3-padding-16 w3-border" type="number" placeholder="How many people?" required name="Number of People in distress"></p>
        <p><input class="w3-input w3-padding-16 w3-border" type="text" placeholder="Area/Locality" required name="Area/Locality"></p>
        <p><input class="w3-input w3-padding-16 w3-border" type="text" placeholder="Description \ Special requirements" required name="Message"></p>
        <p><input class="w3-button w3-black" type="submit" value="REQUEST HELP" onclick=callAlert()></p>
      </form>
    </div>
</div>

<!-- Footer -->
<footer class="w3-center w3-light-grey w3-padding-48 w3-large">
    <p>Powered by <a href="http://www.ndrf.gov.in/" title="NDRF" target="_blank" class="w3-hover-text-green">National Emergency Rescue Team</a></p>
</footer>

{% block two %}
{% endblock %}

</body>
</html>

webapp/templates/webapp/home.html
{% extends 'webapp/base.html' %}

{% block one %}
<!-- About Container -->
<div style="margin-left: 15px; margin-top: 7px; margin-bottom: -50px;"><strong>Legend:</strong>
    <p><img src="http://www.robotwoods.com/dev/misc/bluecircle.png"> Current Location</p>
</div>

<div class="w3-container" id="about">
  <div class="w3-content" style="max-width:700px">
    <a href="{% url 'webapp:get_locations' %}"><h5 class="w3-center w3-padding-64" id="nearby_locs"><span class="w3-tag w3-wide">GET NEARBY SAFE AND UNSAFE LOCATIONS</span></h5></a>
    <p>Click on the above button to find all the nearby safe and unsafe locations in times of emergencies.</p>
    <p>On reaching the area, help us further promote an area as safe or demote it as unsafe using the Mobile Application</p>
  </div>
</div>

{% endblock %}

{% block two %}
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDv2lJm1ggUG25OhwdEtz_GYbWW8qwEK4U&callback=initMap"></script>
<script>
    function callAlert(){
        window.alert('Submitted. Thanks for providing the info');
        return false;
    }
    // Initialize and add the map
    function initMap() {
    var infoWindow = new google.maps.InfoWindow;
    // Try HTML5 geolocation.
    if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(function(position) {
        var curr_pos = {
            lat: position.coords.latitude,
            lng: position.coords.longitude
        };
        var map = new google.maps.Map(
        document.getElementById('map'), {zoom: 15, center: curr_pos});
        var currentMarker = new google.maps.Marker({position: curr_pos, map:map, icon:{
            url:'http://www.robotwoods.com/dev/misc/bluecircle.png'
        }});
        // infoWindow.setPosition(pos);
        // infoWindow.setContent('Location found.');
        // infoWindow.open(map);
        map.setCenter(curr_pos);
        }, function() {
            handleLocationError(true, infoWindow, map.getCenter());
        });
    } else {
      // Browser doesn't support Geolocation
        handleLocationError(false, infoWindow, map.getCenter());
    }
    }

    
  function handleLocationError(browserHasGeolocation, infoWindow, pos) {
    infoWindow.setPosition(pos);
    infoWindow.setContent(browserHasGeolocation ?
                          'Error: The Geolocation service failed.' :
                          'Error: Your browser doesn\'t support geolocation.');
    infoWindow.open(map);
  }
</script>
{% endblock %}

webapp/templates/webapp/home1.html
{% extends 'webapp/base.html' %}

{% block one %}
<!-- About Container -->
<div style="margin-left: 15px; margin-top: 7px; margin-bottom: -50px;"><strong>Legend:</strong>
    <p><img src="http://www.robotwoods.com/dev/misc/bluecircle.png"> Current Location</p>
</div>

<div class="w3-container" id="about">
  <div class="w3-content" style="max-width:700px">
    <a href="{% url 'webapp:get_locations' %}"><h5 class="w3-center w3-padding-64" id="nearby_locs"><span class="w3-tag w3-wide">GET NEARBY SAFE AND UNSAFE LOCATIONS</span></h5></a>
    <p>Click on the above button to find all the nearby safe and unsafe locations in times of emergencies.</p>
    <p>On reaching the area, help us further promote an area as safe or demote it as unsafe using the Mobile Application</p>
  </div>
</div>

{% endblock %}

{% block two %}
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDv2lJm1ggUG25OhwdEtz_GYbWW8qwEK4U&callback=initMap"></script>
<script>
    function callAlert(){
        window.alert('Submitted. Thanks for providing the info');
        return false;
    }
    // Initialize and add the map
    function initMap() {
    var infoWindow = new google.maps.InfoWindow;
    // Try HTML5 geolocation.
    if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(function(position) {
        var curr_pos = {
            lat: position.coords.latitude,
            lng: position.coords.longitude
        };
        var map = new google.maps.Map(
        document.getElementById('map'), {zoom: 15, center: curr_pos});
        var currentMarker = new google.maps.Marker({position: curr_pos, map:map, icon:{
            url:'http://www.robotwoods.com/dev/misc/bluecircle.png'
        }});
        // infoWindow.setPosition(pos);
        // infoWindow.setContent('Location found.');
        // infoWindow.open(map);
        map.setCenter(curr_pos);
        }, function() {
            handleLocationError(true, infoWindow, map.getCenter());
        });
    } else {
      // Browser doesn't support Geolocation
        handleLocationError(false, infoWindow, map.getCenter());
    }
    }

    
  function handleLocationError(browserHasGeolocation, infoWindow, pos) {
    infoWindow.setPosition(pos);
    infoWindow.setContent(browserHasGeolocation ?
                          'Error: The Geolocation service failed.' :
                          'Error: Your browser doesn\'t support geolocation.');
    infoWindow.open(map);
  }
</script>
{% endblock %}

webapp/templates/webapp/locations.html
{% extends 'webapp/base.html' %}

{% block one %}
<div style="margin-left: 15px; margin-top: 7px; margin-bottom: -50  px;"><strong>Legend:</strong>
  <p><img src="http://maps.google.com/mapfiles/ms/icons/green-dot.png"> Safe Location &nbsp; <img src="http://maps.google.com/mapfiles/ms/icons/red-dot.png"> Danger Location </p>
</div>
{%  endblock %}

{% block two %}
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDv2lJm1ggUG25OhwdEtz_GYbWW8qwEK4U&callback=initMap">
</script>
<script>
    // Initialize and add the map
    function initMap() {
    // Try HTML5 geolocation.
    var infoWindow = new google.maps.InfoWindow;
    if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(function(position) {
        var pos = {
            lat: position.coords.latitude,
            lng: position.coords.longitude
        };
        var map = new google.maps.Map(
        document.getElementById('map'), {zoom: 15, center: pos});
        var currentMarker = new google.maps.Marker({position: pos, map:map, icon:{
            url:'http://www.robotwoods.com/dev/misc/bluecircle.png'
        }});
        fetch('http://hackverse-gods.herokuapp.com/get_all_safe_locations')
        .then((response) => {
          return response.json();
        })
        .then((myJson) => {
          for(var i=0;i<myJson.length;i++){
        var safe_loc = {lat: myJson[i].latitude, lng:myJson[i].longitude} 
        var safe_loc_marker = new google.maps.Marker({position: safe_loc, map: map, icon: {
            url:'http://maps.google.com/mapfiles/ms/icons/green-dot.png'
    }})}
        });
        fetch('http://hackverse-gods.herokuapp.com/get_all_distress_locations')
        .then((response) => {
          return response.json();
        })
        .then((myJson) => {
          for(var i=0;i<myJson.length;i++){
        var distress_loc = {lat: myJson[i].latitude, lng:myJson[i].longitude}
        var distress_loc_marker = new google.maps.Marker({position: distress_loc, map: map, icon: {
            url:'http://maps.google.com/mapfiles/ms/icons/red-dot.png'
    }})}})
        // infoWindow.setPosition(pos);
        // infoWindow.setContent('Location found.');
        // infoWindow.open(map);
        map.setCenter(pos);
      }, function() {
        handleLocationError(true, infoWindow, map.getCenter());
      });
    } else {
      // Browser doesn't support Geolocation
      handleLocationError(false, infoWindow, map.getCenter());
    }
    }

    
  function handleLocationError(browserHasGeolocation, infoWindow, pos) {
    infoWindow.setPosition(pos);
    infoWindow.setContent(browserHasGeolocation ?
                          'Error: The Geolocation service failed.' :
                          'Error: Your browser doesn\'t support geolocation.');
    infoWindow.open(map);
  }
</script>
{% endblock %}